# Mandatory settings

name: teds.space
paginate: 25
paginate_path: "/posts/page/:num/"
url: http://tedmor.in
baseurl: /blog
blog_theme: light

# Optional settings

discus_identifier: teds-space # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
rss_enabled: true # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  facebook: morinted # Add your Facebook handle
  github: morinted # Add your GitHub handle
  linkedin: morinted # Add your LinkedIn handle
  twitter: morinted # Add your Twitter handle
  email: morinted@gmail.com # Add your Email address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
permalink: posts/:slug
