version: 2.1

workflow:
  build_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node
        auth:
          username: morinted
          password: $DOCKERHUB_PASSWORD
        environment:
          USER_NAME: Ted Morin
          USER_EMAIL: morinted@gmail.com
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./bin/setup
      - run:
          name: Build
          command: |
              JEKYLL_ENV=production bundle exec jekyll build -d ./_site
              bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --empty-alt-ignore
              cp ./CNAME ./_site/CNAME
  deploy:
    docker:
      - image: circleci/ruby:2.7.0-node
        auth:
          username: morinted
          password: $DOCKERHUB_PASSWORD
        environment:
          USER_NAME: Ted Morin
          USER_EMAIL: morinted@gmail.com
    steps:
      - run:
          name: Deploy
          command: ./bin/automated
